loopring:
  api_keys: ["hNMTkOe7yhFXr9lsEsnd47jYA7DzYuOmHDqXw6Ca3C9x5U8sW2MG15l2jh3c72ub", "74Z9UD45rjH8Vwk3TzgjKmCLyIFireC4wEe0CHECgy7Wey7BHSxV3y066yK770fV"]

discord:
  serverIds:
    cybercrew:
      invite_code: "KWeq4aGF"
      server_id: 874623755165503549
  token: "YOUR DISCORD TOKEN HERE"

