loopring:
  api_keys: ["hNMTkOe7yhFXr9lsEsnd47jYA7DzYuOmHDqXw6Ca3C9x5U8sW2MG15l2jh3c72ub"]

discord:
  serverIds:
    cybercrew:
      invite_code: "KWeq4aGF"
      server_id: 874623755165503549
  token: "YOUR DISCORD TOKEN HERE"

